%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:css<raku-default-styling.css>,
	:custom-raku(),
	:license<Artistic-2.0>,
	:name<raku-styling>,
	:render<move-images-in-css.raku>,
	:scss<raku-default-styling.scss>,
	:template-raku(),
	:jq-script<sidebar.js>,
	:version<0.3.0>,
)