%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:license<Artistic-2.0>,
	:name<sitemap>,
	:report<make-sitemap.raku>,
	:render,
	:version<0.1.0>,
	:root-domain<https://docs.raku.org>,
	:information<root-domain>,
)