#!/usr/bin/env raku
use v6.d;
my %h = (
    'camelia-img' => sub (%prm, %tml) {
        "\n<camelia />"
    },
    'source-wrap' => sub ( %prm, %tml ) {
        '<!DOCTYPE html>' ~ "\n"
        ~ '<html lang="' ~ %prm<config><lang>  ~ '"' ~ "\n"
        ~ '    class="fontawesome-i2svg-active fontawesome-i2svg-complete">' ~ "\n"
        ~ %tml<head-block>.( %prm, %tml ) ~ "\n"
        ~ '<body class="has-navbar-fixed-top">' ~ "\n"
        ~ %tml<top-of-page>.( %prm, %tml ) ~ "\n"
        ~ %tml<header>.( %prm, %tml )  ~ "\n"
        ~ %tml<sidebar>.( %prm, %tml )  ~ "\n"
        ~ %tml<wrapper>.( %prm, %tml )  ~ "\n"
        ~ %tml<footer>.( %prm, %tml )  ~ "\n"
        ~ %tml<js-bottom>.({}, {}) ~ "\n"
        ~ %tml<end-block>.( %prm, %tml ) ~ "\n"
    },
    'header' => sub ( %prm, %tml ) {
        '<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">' ~ "\n"
        ~ '  <div class="container">' ~ "\n"
        ~ '    <div class="navbar-brand navbar-logo">' ~ "\n"
        ~ '      <div class="navbar-logo">' ~ "\n"
        ~ '        <a class="navbar-item" href="/">' ~ "\n"
        ~ '          <img src="/img/camelia-recoloured.png" alt="Raku" width="52.83" height="38">' ~ "\n"
        ~ '        </a>' ~ "\n"
        ~ '        <div class="navbar-logo-tm">tm</div>' ~ "\n"
        ~ '      </div>' ~ "\n"
        ~ '      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu">' ~ "\n"
        ~ '        <span aria-hidden="true"></span>' ~ "\n"
        ~ '        <span aria-hidden="true"></span>' ~ "\n"
        ~ '        <span aria-hidden="true"></span>' ~ "\n"
        ~ '      </a>' ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ '    <div id="navMenu" class="navbar-menu">' ~ "\n"
        ~ '      <div class="navbar-start">' ~ "\n"
        ~ '          <a class="navbar-item" href="/language">' ~ "\n"
        ~ '            Language' ~ "\n"
        ~ '          </a>' ~ "\n"
        ~ '          <a class="navbar-item" href="/type">' ~ "\n"
        ~ '            Types' ~ "\n"
        ~ '          </a>' ~ "\n"
        ~ '          <a class="navbar-item" href="/routine">' ~ "\n"
        ~ '            Routines' ~ "\n"
        ~ '          </a>' ~ "\n"
        ~ '          <a class="navbar-item" href="/programs">' ~ "\n"
        ~ '            Programs' ~ "\n"
        ~ '          </a>' ~ "\n"
        ~ '        <a class="navbar-item" href="https://raku.org">' ~ "\n"
        ~ '          Raku Homepage' ~ "\n"
        ~ '        </a>' ~ "\n"
        ~ '        <a class="navbar-item" href="https://webchat.freenode.net/?channels=#raku">' ~ "\n"
        ~ '          Chat with us' ~ "\n"
        ~ '        </a>' ~ "\n"
        ~ '        <div class="navbar-item has-dropdown is-hoverable">' ~ "\n"
        ~ '          <a class="navbar-link">' ~ "\n"
        ~ '            More' ~ "\n"
        ~ '          </a>' ~ "\n"
        ~ '          <div class="navbar-dropdown">' ~ "\n"
        ~ '            <a class="navbar-item" href="/search">' ~ "\n"
        ~ '              Extended Search' ~ "\n"
        ~ '            </a>' ~ "\n"
        ~ '            <hr class="navbar-divider">' ~ "\n"
        ~ '            <a class="navbar-item" href="/about">' ~ "\n"
        ~ '              About' ~ "\n"
        ~ '            </a>' ~ "\n"
        ~ '            <hr class="navbar-divider">' ~ "\n"
        ~ '            <a class="navbar-item has-text-red" href="https://github.com/raku/doc/blob/master/CONTRIBUTING.md#reporting-bugs">' ~ "\n"
        ~ '              Report an issue with the content' ~ "\n"
        ~ '            </a>' ~ "\n"
        ~ '            <hr class="navbar-divider">' ~ "\n"
        ~ '            <a class="navbar-item has-text-red" href="https://github.com/Altai-man/docs.raku.org/issues">' ~ "\n"
        ~ '              Report an issue of this site' ~ "\n"
        ~ '            </a>' ~ "\n"
        ~ '          </div>' ~ "\n"
        ~ '        </div>' ~ "\n"
        ~ '      </div>' ~ "\n"
        ~ '      <div class="navbar-end navbar-search-wrapper">' ~ "\n"
        ~ '        <div class="navbar-item">' ~ "\n"
        ~ '          <div class="field has-addons">' ~ "\n"
        ~ '            <div id="search" class="control">' ~ "\n"
        ~ '              <input id="query" class="input ui-autocomplete-input" type="text" placeholder="🔍" autocomplete="off">' ~ "\n"
        ~ '            </div>' ~ "\n"
        ~ '            <div class="control">' ~ "\n"
        ~ '              <a class="button is-primary">' ~ "\n"
        ~ '                <span class="icon">' ~ "\n"
        ~ '                  <i class="fas fa-search "></i>' ~ "\n"
        ~ '                </span>' ~ "\n"
        ~ '              </a>' ~ "\n"
        ~ '            </div>' ~ "\n"
        ~ '          </div>' ~ "\n"
        ~ '        </div>' ~ "\n"
        ~ '        <div id="navbar-search" class="navbar-search-autocomplete" style="display: none;">' ~ "\n"
        ~ '            <ul id="ui-id-1"' ~ "\n"
        ~ '                tabindex="0"' ~ "\n"
        ~ '                class="ui-menu ui-widget ui-widget-content ui-autocomplete ui-front"' ~ "\n"
        ~ '                style="display: none;">' ~ "\n"
        ~ '            </ul>' ~ "\n"
        ~ '        </div>' ~ "\n"
        ~ '        <div id="navbar-search-empty"' ~ "\n"
        ~ '            class="navbar-search-autocomplete">' ~ "\n"
        ~ '          <a id="try-web-search" href="https://www.google.com/" class="button" target="blank">' ~ "\n"
        ~ '            Not found, but you can try site search</a>' ~ "\n"
        ~ '        </div>' ~ "\n"
        ~ '      </div>' ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ '  </div>' ~ "\n"
        ~ '</nav>' ~ "\n";
    },
    'sidebar' => sub ( %prm, %tml ) {
        return '' unless %prm<toc>;
        '<div id="mainSidebar" class="raku-sidebar" style="width:0px; display:none;">' ~ "\n"
        ~ '  <div class="field">' ~ "\n"
        ~ '    <label class="label has-text-centered">Table of Contents</label>' ~ "\n"
        ~ '    <div class="control has-icons-right">' ~ "\n"
        ~ '      <input id="toc-filter" class="input" type="text" placeholder="Filter">' ~ "\n"
        ~ '      <span class="icon is-right has-text-grey">' ~ "\n"
        ~ '        <i class="fas fa-search is-medium"></i>' ~ "\n"
        ~ '      </span>' ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ '  </div>' ~ "\n"
        ~ '  <div class="raku-sidebar-body">' ~ "\n"
        ~ '    <aside id="toc-menu" class="menu">' ~ "\n"
        ~ %prm<toc>  ~ "\n"
        ~ '    </aside>' ~ "\n"
        ~ '  </div>' ~ "\n"
        ~ '</div>' ~ "\n"
    },
    'wrapper' => sub ( %prm, %tml ) {
        '<div id="wrapper">' ~ "\n"
        ~ %tml<page-header>.( %prm, %tml )  ~ "\n"
        ~ %tml<page-content>.( %prm, %tml )  ~ "\n"
        ~ %tml<page-footnotes>.( %prm, %tml )  ~ "\n"
        ~ %tml<page-generated>.( %prm, %tml )  ~ "\n"
        ~ '</div>' ~ "\n"
    },
    'page-header' => sub ( %prm, %tml ) {
        '<section class="container px-4">' ~ "\n"
        ~ '    <div class="raku page-title has-text-centered">' ~ "\n"
        ~ %prm<title>  ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ '    <div class="raku page-subtitle has-text-centered">' ~ "\n"
        ~ %prm<subtitle>  ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ %prm<page-edit>  ~ "\n"
        ~ '</section>' ~ "\n"
    },
    'page-content' => sub ( %prm, %tml ) {
        '<section class="raku page-content">' ~ "\n"
        ~ '    <div class="container px-4">' ~ "\n"
        ~ %prm<body>  ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ '</section>' ~ "\n"
    },
    'page-footnotes' => sub ( %prm, %tml ) {
        return '' unless %prm<footnotes>;
        '<section class="page-footnotes">' ~ "\n"
        ~ '    <div class="container">' ~ "\n"
        ~ %prm<footnotes>  ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ '</section>' ~ "\n"
    },
    'page-generated' => sub ( %prm, %tml ) {
        '<section class="page-generated">' ~ "\n"
        ~ '    <div class="container has-text-centered">' ~ "\n"
        ~ '      <p> Generated from ' ~ %prm<config><path>
        ~ ' at ' ~ DateTime(now).truncated-to('second') ~ '</p>' ~ "\n"
        ~ '    </div>' ~ "\n"
        ~ '</section>' ~ "\n";
    },
    'footer' => sub ( %prm, %tml ) {
        '<footer class="footer main-footer">' ~ "\n"
        ~ '  <div class="container px-4">' ~ "\n"
        ~ '    <nav class="level">' ~ "\n"
        ~ '        <div class="level-left">' ~ "\n"
        ~ '          <div class="level-item">' ~ "\n"
        ~ '              <a href="/about">About</a>' ~ "\n"
        ~ '           </div>' ~ "\n"
        ~ '            <div class="level-item">' ~ "\n"
        ~ '              <a id="toggle-theme">Toggle theme</a>' ~ "\n"
        ~ '            </div>' ~ "\n"
        ~ '        </div>' ~ "\n"
        ~ '        <div class="level-right">' ~ "\n"
        ~ '          <div class="level-item">' ~ "\n"
        ~ '            <p>' ~ "\n"
        ~ '              This website is licensed under' ~ "\n"
        ~ '              <a href="https://raw.githubusercontent.com/Raku/doc/master/LICENSE">the Artistic License 2.0</a>' ~ "\n"
        ~ '            </p>' ~ "\n"
        ~ '          </div>' ~ "\n"
        ~ '        </div>' ~ "\n"
        ~ '    </nav>' ~ "\n"
        ~ '  </div>' ~ "\n"
        ~ '</footer>' ~ "\n"
    },
    'page-edit' => sub ( %prm, %tml ) {
        return '' unless %prm<config><path> ~~ / ^ .+ ('docs/' .+) $ /;
        '<div class="page-edit">' ~ "\n"
        ~ '    <a class="button page-edit-button"' ~ "\n"
        ~ '       href="https://github.com/Raku/doc/edit/master/'
        ~           %tml<escaped>.(~$0) ~ '" title="Edit this page.">' ~ "\n"
        ~ '      <span class="icon is-right">' ~ "\n"
        ~ '        <i class="fas fa-pen-alt is-medium"></i>' ~ "\n"
        ~ '      </span>' ~ "\n"
        ~ '    </a>' ~ "\n"
        ~ '  </div>' ~ "\n"
    },
    'end-block' => sub ( %prm, %tml ) {
        '<script' ~ "\n"
        ~ '    defer=""' ~ "\n"
        ~ '    src="https://use.fontawesome.com/releases/v5.3.1/js/all.js">' ~ "\n"
        ~ '</script>' ~ "\n"
        ~ '<div' ~ "\n"
        ~ '    role="status"' ~ "\n"
        ~ '    aria-live="assertive"' ~ "\n"
        ~ '    aria-relevant="additions"' ~ "\n"
        ~ '    class="ui-helper-hidden-accessible">' ~ "\n"
        ~ '</div>' ~ "\n"
    },
);
say %h;
