%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku<tablesearch-block.raku>,
	:license<Artistic-2.0>,
	:name<tablesearch>,
	:render,
	:template-raku<tablesearch-temps.raku>,
	:version<0.1.0>,
	:jquery<tablesearch.js>,
)