%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:custom-raku<block.raku>,
	:license<Artistic-2.0>,
	:name<generated>,
	:render<get-commit-id.raku>,
	:template-raku<template.raku>,
	:version<0.1.2>,
	:css<generated.css>
)