%(
	:auth<collection>,
	:authors(
		"finanalyst",
	),
	:css<latex-render.css>,
	:custom-raku<latex-block.raku>,
	:license<Artistic-2.0>,
	:render,
	:template-raku<latex-template.raku>,
	:version<0.1.0>,
)